[package]
name = "motd"
version = "0.1.0"
edition = "2021"

[features]
debug = []
# https://docs.solana.com/developing/on-chain-programs/developing-rust#project-layout
#
# When toggled on this feature will cause the crate to not compile a
# bpf entrypoint.
#
# See the corresponding `#[cfg(not(feature = "exclude_entrypoint"))]`
# in lib.rs. This is needed so that other Solana programs can import
# helper functions from this library without causing symbol conflicts
# with our entrypoint.
exclude_entrypoint = []
custom-heap = []
custom-panic = []

[lib]
crate-type = ["cdylib", "lib"]
name = "motd"                  # This will determine the filename (motd.so)

[dependencies]
solana-program = "3.0.0"
solana-system-interface = { version = "2", features = ["bincode"] }
spl-token = { version = "4.0" }
borsh = "1.6"
thiserror = "1.0"
base64ct = "=1.6.0"
blake3 = "=1.8.2"

[dev-dependencies]
solana-program-test = "3.0.0" 
solana-sdk = "3.0.0"
borsh = "1.6"
tokio = { version = "1", features = ["full"] }

[package.metadata.solana]
program-id = "8pRUcpXfWot7uhCyF8pH4ebz48hReW83VXwPzSh14DKy"
